### ISSUE TITLE
1.3 处理好的工程包  下的两个链接文件好像都无法下载

### ISSUE THREAD

**Issue by dlk1932** [Lordog/dive-into-llms#14]
![image](https://github.com/user-attachments/assets/56ed2602-3d3b-40ea-ac82-480680f7cb3c)

**Comment by Lordog** [comment]
google drive下载链接需挂代理。国内可以试试从飞书里面下载：https://nby1ut42mx.feishu.cn/docx/Luy4dbe4OoXqOzxUDlGcjnDpnuf。

**Comment by dlk1932** [comment]
您好，邮件已收到！我会尽快处理的。
